### ISSUE TITLE
Implement endpoint: /themes/info

### ISSUE THREAD

**Issue by chuckadams** [aspirepress/AspireCloud#41]
A stub implementation currently exists that actually returns data from the DB, but doesn't actually process arguments other than pagination.  Still need a full implementation of all actions.

**Comment by eadamsatx** [comment]
More info about about this endpoint is available here: https://codex.wordpress.org/WordPress.org_API#Themes

Among the important parts of the above documentation is how "action" is implemented- this is really 4 endpoints in one.

query_themes - A a list of themes.
theme_information - Information about a specific theme.
hot_tags - List of the most popular theme tags.
feature_list - List of valid theme tags.

query_themes and theme_information are the most important. If this issue seems too big, feel free to open for a specific action. We can always break this issue down further.

**Comment by chuckadams** [comment]
reopening, since hot_tags is not yet implemented

**Comment by chuckadams** [comment]
Implementation here: https://github.com/WordPress/wordpress.org/blob/bc358fb59cbbaf1302019796699ab4d94b6e8e4d/wordpress.org/public_html/wp-content/plugins/theme-directory/class-themes-api.php#L165

Interestingly there's a `get_commercial_shops` action in there, not even noted in the documentation for that very line...

**Comment by chuckadams** [comment]
With #81 and #82 merged, this one is donesies.  💃
